### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Tricertops** [iMartinKiss/Objective-Chain#1]
#### Current iteration: 0.2.0

_Note: Features, where only test are missing, should work as expected. They are just not formally tested._
##### Producers
- [x] Command + Tests
- [x] **Hub** + Tests
- [x] **Property** + Tests
- [x] **Notificator** + Tests
- [x] **Timer** + Tests
- [x] **Invoker** + Tests
- [x] Action Target (missing **Tests**)
- [ ] Task **??** Does it make sense to abstract a _task_ as a Producer of values? Maybe.
##### Mediators
- [x] **Bridge** + Tests
- [x] **Context** + Tests
- [x] UIKit Contexts (missing **Tests**)
- [x] **Filter** + Tests
- [ ] Gateway
- [x] **Throttle** + Tests
- [x] Interpolator + Tests
- [ ] Delayer ?
- [ ] Reproducer ?
##### Consumers
- [x] **Subscriber** + Tests
- [x] **Property** + Tests
- [x] Switch + Tests
- [ ] UIButton setters (missing **Tests**)
##### Transformers
- [x] **Basic** + Tests
- [x] **Collections** (NSArray, NSDictionary, …) + Tests
- [x] **Math** + Tests
- [x] **NSString** and related (missing **Tests**)
- [x] **NSDate** and related (missing **Tests**)
- [x] NSData (missing **Tests**)
- [x] CGPoint (missing **Tests**)
- [x] CGSize (missing **Tests**)
- [x] CGRect (missing **Tests**)
- [x] CGAffineTransform (missing **Tests**)
- [x] UIEdgeInsets (missing **Tests**)
- [x] CATransform3D (missing **Tests**)
- [x] UIColor
- [x] UIImage
##### Predicates
- [x] **Basic** (missing **Tests**)
- [x] Geometry
##### Utilities
- [x] Decomposer + Tests
- [x] **Queue** + Tests
- [x] Key-Path Accessor + Tests
- [x] Structure Accessor + Tests
- [x] Invocation Catcher + Tests
